In [1]:
import numpy as np

#### Benchmark, function


In [2]:
from MFEA_lib.tasks.Benchmark import CEC17_benchmark
from MFEA_lib.tasks.Benchmark import GECCO20_benchmark_50tasks

In [3]:
from MFEA_lib.tasks.function import *

In [3]:
gecco1 = GECCO20_benchmark_50tasks.get_items(ID = 10)

In [4]:
for t in gecco1:
    print(t.name)
len(gecco1)

Ackley: [-50, 50]^50
Rastrigin: [-50, 50]^50
Griewank: [-100, 100]^50
Rosenbrock: [-0.5, 0.5]^50
Rosenbrock: [-500, 500]^50
Ackley: [-50, 50]^50
Rastrigin: [-50, 50]^50
Griewank: [-100, 100]^50
Rosenbrock: [-0.5, 0.5]^50
Rosenbrock: [-500, 500]^50
Ackley: [-50, 50]^50
Rastrigin: [-50, 50]^50
Griewank: [-100, 100]^50
Rosenbrock: [-0.5, 0.5]^50
Rosenbrock: [-500, 500]^50
Ackley: [-50, 50]^50
Rastrigin: [-50, 50]^50
Griewank: [-100, 100]^50
Rosenbrock: [-0.5, 0.5]^50
Rosenbrock: [-500, 500]^50
Ackley: [-50, 50]^50
Rastrigin: [-50, 50]^50
Griewank: [-100, 100]^50
Rosenbrock: [-0.5, 0.5]^50
Rosenbrock: [-500, 500]^50
Ackley: [-50, 50]^50
Rastrigin: [-50, 50]^50
Griewank: [-100, 100]^50
Rosenbrock: [-0.5, 0.5]^50
Rosenbrock: [-500, 500]^50
Ackley: [-50, 50]^50
Rastrigin: [-50, 50]^50
Griewank: [-100, 100]^50
Rosenbrock: [-0.5, 0.5]^50
Rosenbrock: [-500, 500]^50
Ackley: [-50, 50]^50
Rastrigin: [-50, 50]^50
Griewank: [-100, 100]^50
Rosenbrock: [-0.5, 0.5]^50
Rosenbrock: [-500, 500]^50
Ackley: 

50

In [5]:
tasks = CEC17_benchmark.get_10tasks_benchmark()

In [6]:
for t in tasks:
    print(t.name)

Sphere: [-100, 100]^50
Sphere: [-100, 100]^50
Sphere: [-100, 100]^50
Weierstrass: [-0.5, 0.5]^25
Rosenbrock: [-50, 50]^50
Ackley: [-50, 50]^50
Weierstrass: [-0.5, 0.5]^50
Schwefel: [-500, 500]^50
Griewank: [-100, 100]^50
Rastrigin: [-50, 50]^50


In [7]:
for t in tasks:
    print(t.global_optimal[[0, -1]])

[0 0]
[80 80]
[-80 -80]
[-0.4 -0.4]
[-1 -1]
[40 40]
[-0.4 -0.4]
[0 0]
[-80  80]
[ 40 -40]


In [8]:
tasks[9].encode(np.append(np.array([0] * 25), np.array([0] * 25)))

array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9,
       0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [9]:
print(tasks[0](tasks[0].encode(np.array([0] * 50))))
print(tasks[1](tasks[1].encode(np.array([0] * 50))))
print(tasks[2](tasks[2].encode(np.array([0] * 50))))
print(tasks[3](tasks[3].encode(np.array([0] * 25))))
print(tasks[4](tasks[4].encode(np.array([1] * 50))))
print(tasks[5](tasks[5].encode(np.array([0] * 50))))
print(tasks[6](tasks[6].encode(np.array([0] * 50))))
print(tasks[7](tasks[7].encode(np.array([420.9687] * 50))))
print(tasks[8](tasks[8].encode(np.append(np.array([0] * 25), np.array([0] * 25)))))
print(tasks[9](tasks[9].encode(np.append(np.array([0] * 25), np.array([0] * 25)))))


0.0
0.0
0.0
0.0
0.0
4.440892098500626e-16
0.0
0.0006363918728311546
0.0
0.0


In [10]:
tasks[7].encode(np.array([420.9687] * 50))[[0, -1]]

array([0.9209687, 0.9209687])

In [11]:
tasks[7].decode(tasks[7].encode(np.array([420.9687] * 50)))[[0, -1]]

array([420.9687, 420.9687])

In [12]:
print(tasks[0].encode(np.array([0] * 50))[[0, -1]])
print(tasks[1].encode(np.array([0] * 50))[[0, -1]])
print(tasks[2].encode(np.array([0] * 50))[[0, -1]])
print(tasks[3].encode(np.array([0] * 25))[[0, -1]])
print(tasks[4].encode(np.array([1] * 50))[[0, -1]])
print(tasks[5].encode(np.array([0] * 50))[[0, -1]])
print(tasks[6].encode(np.array([0] * 50))[[0, -1]])
print(tasks[7].encode(np.array([420.9687] * 50))[[0, -1]])
print(tasks[8].encode(np.array([0] * 50))[[0, -1]])
print(tasks[9].encode(np.array([0] * 50))[[0, -1]])

[0.5 0.5]
[0.9 0.9]
[0.1 0.1]
[0.1 0.1]
[0.5 0.5]
[0.9 0.9]
[0.1 0.1]
[0.9209687 0.9209687]
[0.1 0.9]
[0.9 0.1]


#### GA

In [13]:
import numpy as np
from MFEA_lib.GA import population_init, skill_factor_best_task, factorial_cost, factorial_rank
from MFEA_lib.operators import CrossOver


In [14]:
test_pop, test_skf_arr = population_init(
    N = 10, 
    num_tasks= 10, 
    d = 50, 
    min_val= 0, max_val= 1
)
print(test_pop.shape)
print([len(np.where(test_skf_arr == i)[0]) for i in range(5)])
print(np.min(test_pop), np.max(test_pop))

(100, 50)
[10, 10, 10, 10, 10]
5.046903590755214e-05 0.9998613623159114


In [15]:
test_skf_arr = skill_factor_best_task(test_pop, tasks)
print([len(np.where(test_skf_arr == i)[0]) for i in range(5)])

[10, 10, 10, 10, 10]


In [16]:
f_cost = factorial_cost(test_pop, test_skf_arr, tasks)
print(f_cost.shape)

(100,)


In [17]:
f_rank = factorial_rank(f_cost, test_skf_arr, len(tasks))
print(f_rank.shape)
print(np.min(f_rank), np.max(f_rank))

(100,)
1 10


In [21]:
a = np.zeros(10)
b = np.ones(10)
CrossOver.SBX_CrossOver()(a, b, 'intra')

(array([0.        , 0.99764958, 0.96345557, 0.        , 0.01772881,
        0.        , 1.        , 1.        , 0.9143561 , 0.98241157]),
 array([1.        , 0.00235042, 0.03654443, 1.        , 0.98227119,
        1.        , 0.        , 0.        , 0.0856439 , 0.01758843]))

#### operators

In [ ]:
from MFEA_lib.operators.Mutation import Polynomial_Mutation
import numpy as np
import time

In [ ]:
Polynomial_Mutation(nm = 15)(np.array([0.5]*5))


array([0.5       , 0.5       , 0.52484951, 0.5       , 0.5       ])